from django.utils.translation import gettext_lazy as _

movies = [
    _("A Christmas Story"),
    _("A Fish Called Wanda"),
    _("A Nightmare on Elm Street"),
    _("Adventures in Babysitting"),
    _("After Hours"),
    _("Airplane!"),
    _("Akira"),
    _("Amadeus"),
    _("Au Revoir, les enfants"),
    _("Baby Boom"),
    _("Back to the Future"),
    _("Batman"),
    _("Beetlejuice"),
    _("Better Off Dead"),
    _("Beverly Hills Cop"),
    _("Big Trouble in Little China"),
    _("Big"),
    _("Bill & Ted's Excellent Adventure"),
    _("Blade Runner"),
    _("Blue Velvet"),
    _("Body Heat"),
    _("Broadcast News"),
    _("Caddyshack"),
    _("Coming to America"),
    _("Commando"),
    _("Dead Poets Society"),
    _("Desperately Seeking Susan"),
    _("Die Hard"),
    _("Dirty Dancing"),
    _("Do the Right Thing"),
    _("Dragonslayer"),
    _("Drugstore Cowboy"),
    _("E.T. the Extra-Terrestrial"),
    _("Eddie Murphy: Delirious"),
    _("Escape From New York"),
    _("Evil Dead 2"),
    _("Fast Times at Ridgemont High"),
    _("Ferris Bueller's Day Off"),
    _("Field of Dreams"),
    _("Flashdance"),
    _("Flight of the Navigator"),
    _("Footloose"),
    _("Friday the 13th"),
    _("Full Metal Jacket"),
    _("Ghostbusters"),
    _("Grave of the Fireflies"),
    _("Gremlins"),
    _("Hannah and Her Sisters"),
    _("Heathers"),
    _("Highlander"),
    _("Indiana Jones and the Last Crusade"),
    _("Indiana Jones and the Temple of Doom"),
    _("Krush Groove"),
    _("Labyrinth"),
    _("Ladyhawke"),
    _("Lethal Weapon"),
    _("Little Shop of Horrors"),
    _("Lost in America"),
    _("Mad Max 2"),
    _("Moonstruck"),
    _("My Left Foot"),
    _("My Life as a Dog"),
    _("My Neighbor Totoro"),
    _("Mystery Train"),
    _("Mystic Pizza"),
    _("National Lampoon's Vacation"),
    _("Near Dark"),
    _("Paris, Texas"),
    _("Planes, Trains and Automobiles"),
    _("Platoon"),
    _("Poltergeist"),
    _("Predator"),
    _("Pretty in Pink"),
    _("Purple Rain"),
    _("Raging Bull"),
    _("Raiders of the Lost Ark"),
    _("Raising Arizona"),
    _("Ran"),
    _("Re-Animator"),
    _("Real Genius"),
    _("Repo Man"),
    _("Return to Oz"),
    _("Revenge of the Nerds"),
    _("Risky Business"),
    _("RoboCop"),
    _("Say Anything..."),
    _("Scanners"),
    _("Scarface"),
    _("Short Circuit"),
    _("Sid & Nancy"),
    _("Sixteen Candles"),
    _("Sleepaway Camp"),
    _("Spaceballs"),
    _("St. Elmo's Fire"),
    _("Stand by Me"),
    _("Star Wars: Episode V -- The Empire Strikes Back"),
    _("Star Wars: Episode VI -- Return of the Jedi"),
    _("Steel Magnolias"),
    _("Stop Making Sense"),
    _("Stripes"),
    _("Terms of Endearment"),
    _("The Adventures of Buckaroo Banzai Across the Eighth Dimension"),
    _("The Blues Brothers"),
    _("The Boat"),
    _("The Breakfast Club"),
    _("The Color Purple"),
    _("The Goonies"),
    _("The Karate Kid"),
    _("The Killer"),
    _("The Land Before Time"),
    _("The Last Starfighter"),
    _("The Little Mermaid"),
    _("The Lost Boys"),
    _("The Naked Gun"),
    _("The Neverending Story"),
    _("The Princess Bride"),
    _("The Return of the Living Dead"),
    _("The Shining"),
    _("The Terminator"),
    _("The Thing"),
    _("The Toxic Avenger"),
    _("The Transformers: The Movie"),
    _("The Untouchables"),
    _("They Live"),
    _("This Is Spinal Tap"),
    _("Time Bandits"),
    _("To Live and Die in L.A."),
    _("Tootsie"),
    _("Top Gun"),
    _("Trading Places"),
    _("Tron"),
    _("UHF"),
    _("Valley Girl"),
    _("Wall Street"),
    _("WarGames"),
    _("Weird Science"),
    _("When Harry Met Sally..."),
    _("Who Framed Roger Rabbit"),
    _("Willow"),
    _("Working Girl"),
]
