movies = [
    "A Christmas Story",
    "A Fish Called Wanda",
    "A Nightmare on Elm Street",
    "Adventures in Babysitting",
    "After Hours",
    "Airplane!",
    "Akira",
    "Amadeus",
    "Au Revoir, les enfants",
    "Baby Boom",
    "Back to the Future",
    "Batman",
    "Beetlejuice",
    "Better Off Dead",
    "Beverly Hills Cop",
    "Big Trouble in Little China",
    "Big",
    "Bill &amp; Ted's Excellent Adventure",
    "Blade Runner",
    "Blue Velvet",
    "Body Heat",
    "Broadcast News",
    "Caddyshack",
    "Coming to America",
    "Commando",
    "Dead Poets Society",
    "Desperately Seeking Susan",
    "Die Hard",
    "Dirty Dancing",
    "Do the Right Thing",
    "Dragonslayer",
    "Drugstore Cowboy",
    "E.T. the Extra-Terrestrial",
    "Eddie Murphy: Delirious",
    "Escape From New York",
    "Evil Dead 2",
    "Fast Times at Ridgemont High",
    "Ferris Bueller's Day Off",
    "Field of Dreams",
    "Flashdance",
    "Flight of the Navigator",
    "Footloose",
    "Friday the 13th",
    "Full Metal Jacket",
    "Ghostbusters",
    "Grave of the Fireflies",
    "Gremlins",
    "Hannah and Her Sisters",
    "Heathers",
    "Highlander",
    "Indiana Jones and the Last Crusade",
    "Indiana Jones and the Temple of Doom",
    "Krush Groove",
    "Labyrinth",
    "Ladyhawke",
    "Lethal Weapon",
    "Little Shop of Horrors",
    "Lost in America",
    "Mad Max 2",
    "Moonstruck",
    "My Left Foot",
    "My Life as a Dog",
    "My Neighbor Totoro",
    "Mystery Train",
    "Mystic Pizza",
    "National Lampoon's Vacation",
    "Near Dark",
    "Paris, Texas",
    "Planes, Trains and Automobiles",
    "Platoon",
    "Poltergeist",
    "Predator",
    "Pretty in Pink",
    "Purple Rain",
    "Raging Bull",
    "Raiders of the Lost Ark",
    "Raising Arizona",
    "Ran",
    "Re-Animator",
    "Real Genius",
    "Repo Man",
    "Return to Oz",
    "Revenge of the Nerds",
    "Risky Business",
    "RoboCop",
    "Say Anything...",
    "Scanners",
    "Scarface",
    "Short Circuit",
    "Sid &amp; Nancy",
    "Sixteen Candles",
    "Sleepaway Camp",
    "Spaceballs",
    "St. Elmo's Fire",
    "Stand by Me",
    "Star Wars: Episode V -- The Empire Strikes Back",
    "Star Wars: Episode VI -- Return of the Jedi",
    "Steel Magnolias",
    "Stop Making Sense",
    "Stripes",
    "Terms of Endearment",
    "The Adventures of Buckaroo Banzai Across the Eighth Dimension",
    "The Blues Brothers",
    "The Boat",
    "The Breakfast Club",
    "The Color Purple",
    "The Goonies",
    "The Karate Kid",
    "The Killer",
    "The Land Before Time",
    "The Last Starfighter",
    "The Little Mermaid",
    "The Lost Boys",
    "The Naked Gun",
    "The Neverending Story",
    "The Princess Bride",
    "The Return of the Living Dead",
    "The Shining",
    "The Terminator",
    "The Thing",
    "The Toxic Avenger",
    "The Transformers: The Movie",
    "The Untouchables",
    "They Live",
    "This Is Spinal Tap",
    "Time Bandits",
    "To Live and Die in L.A.",
    "Tootsie",
    "Top Gun",
    "Trading Places",
    "Tron",
    "UHF",
    "Valley Girl",
    "Wall Street",
    "WarGames",
    "Weird Science",
    "When Harry Met Sally...",
    "Who Framed Roger Rabbit",
    "Willow",
    "Working Girl",
]
