# Generated by Django 4.0.3 on 2022-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="sessionid",
            field=models.CharField(db_index=True, default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="added",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
