# Generated by Django 4.0.3 on 2022-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_todo_sessionid_alter_todo_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="sessionid",
            new_name="session_key",
        ),
    ]
