# Generated by Django 5.1.2 on 2025-10-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_rename_sessionid_todo_session_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakingNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Breaking news",
            },
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "ToDo", "verbose_name_plural": "ToDos"},
        ),
    ]
