name: pytest-django CI

on:
  push:
    branches: [ "tetra-package", "ci" ]
  pull_request:
    branches: [ "tetra-package", "ci" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8,3.11,3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run Tests
      run: |
        cd tests
        pytest
